### ISSUE TITLE
UC – 015| LISTAR PERSONAL DE SALUD

### ISSUE THREAD

**Issue by mynameisntalejo** [unlp-taller-tecnologias/2016-grupo-2#15]

**Comment by ldelia** [comment]
No mostrar ID.
Género le falta acento.
La edad es calculada. Se carga fecha de nacimiento

**Comment by ldelia** [comment]
Género le falta acento.

**Comment by ldelia** [comment]
En el show no mostrar ID

**Comment by ldelia** [comment]
Cual es el sentido de que el usuario este ligado a un personal? (no lo recuerdo...)

**Comment by ldelia** [comment]
Cerrar
