### ISSUE TITLE
UC – 040 | ELIMINACIÓN DE PACIENTE

### ISSUE THREAD

**Issue by mynameisntalejo** [unlp-taller-tecnologias/2016-grupo-2#40]

**Comment by ldelia** [comment]
- Todo bóton de eliminación debe pedir confirmación al usuario

**Comment by ldelia** [comment]
Cuando elimino un paciente aparece el mensaje: "Se ha eliminado exitósamente la Anestesia."

**Comment by ldelia** [comment]
Cerrar
